In [1]:
import xgboost as xgb
from utils import get_data
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline
from sklearn.svm import SVC, LinearSVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, classification_report
SEP = '*'*10

In [2]:

for t in range(1, 37):
    if t == 11: continue
    X_train = []
    X_test = []
    test_subjects = [t]
    for i in range(1, 37):
        if i == 11: continue
        if i in test_subjects:
            X_test.append(get_data(i))
        else:
            X_train.append(get_data(i))

    X_train = np.vstack(X_train)
    y_train = X_train[:, -1]
    X_train = X_train[:, :-1]

    X_test = np.vstack(X_test)
    y_test = X_test[:, -1]
    X_test = X_test[:, :-1]

    scaler = StandardScaler()
    X_train = scaler.fit_transform(X_train)
    X_test = scaler.transform(X_test)
    

    scale_pos_weight = sum(y_train == 0) / sum(y_train == 1)
    clf = xgb.XGBClassifier(scale_pos_weight=scale_pos_weight, objective='binary:logistic')
    clf.fit(X_train, y_train)
    y_pred = clf.predict(X_test)
    print(f'result on test: {t}')
    print(classification_report(y_test, y_pred))
    print(confusion_matrix(y_test, y_pred))
    print(SEP)

result on test: 1
              precision    recall  f1-score   support

         0.0       0.77      0.89      0.83      4153
         1.0       0.18      0.09      0.12      1200

    accuracy                           0.71      5353
   macro avg       0.48      0.49      0.47      5353
weighted avg       0.64      0.71      0.67      5353

[[3688  465]
 [1097  103]]
**********
result on test: 2
              precision    recall  f1-score   support

         0.0       0.98      0.74      0.84      9561
         1.0       0.00      0.00      0.00       130

    accuracy                           0.73      9691
   macro avg       0.49      0.37      0.42      9691
weighted avg       0.97      0.73      0.83      9691

[[7068 2493]
 [ 130    0]]
**********
result on test: 3
              precision    recall  f1-score   support

         0.0       0.75      0.86      0.80      6167
         1.0       0.03      0.01      0.02      1800

    accuracy                           0.66      796

In [3]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

         0.0       0.93      0.95      0.94     28649
         1.0       0.31      0.25      0.28      2600

    accuracy                           0.89     31249
   macro avg       0.62      0.60      0.61     31249
weighted avg       0.88      0.89      0.89     31249



In [4]:
confusion_matrix(y_test, y_pred)

array([[27178,  1471],
       [ 1939,   661]], dtype=int64)